# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (CRIM IS cluster1) AND (ZN IS cluster1) AND (INDUS IS cluster1) AND (NOX IS cluster1) AND (RM IS cluster1) AND (AGE IS cluster1) AND (DIS IS cluster1) AND (RAD IS cluster1) AND (TAX IS cluster1) AND (PTRATIO IS cluster1) AND (LSTAT IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (CRIM IS cluster2) AND (ZN IS cluster2) AND (INDUS IS cluster2) AND (NOX IS cluster2) AND (RM IS cluster2) AND (AGE IS cluster2) AND (DIS IS cluster2) AND (RAD IS cluster2) AND (TAX IS cluster2) AND (PTRATIO IS cluster2) AND (LSTAT IS cluster2) THEN (OUTPUT IS fun2)"
FS.add_rules([RULE1, RULE2])

FS.set_output_function('fun1', '-2.054325e-01*CRIM+1.533751e-01*ZN+-1.306243e-01*INDUS+-3.271493e+01*NOX+-1.415605e+00*RM+5.659895e-02*AGE+-3.222925e+00*DIS+3.437049e-01*RAD+-9.705257e-03*TAX+-7.751249e-01*PTRATIO+-9.752345e-01*LSTAT+8.551608e+01')
FS.set_output_function('fun2', '-1.353512e-01*CRIM+2.003289e-02*ZN+4.216271e-02*INDUS+-8.224325e+00*NOX+8.191747e+00*RM+-2.950258e-02*AGE+-9.309824e-01*DIS+2.565554e-01*RAD+-1.342065e-02*TAX+-7.075781e-01*PTRATIO+-2.221958e-01*LSTAT+-9.693022e-03')

FS_1 = FuzzySet(function=Gaussian_MF(30.336472, 158.829008), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(-19.098463, 43.594899), term='cluster2')
MF_CRIM = LinguisticVariable([FS_1, FS_2], concept='CRIM' , universe_of_discourse=(0.00632, 73.5341))
FS.add_linguistic_variable('CRIM', MF_CRIM)

FS_3 = FuzzySet(function=Gaussian_MF(-17.327374, 66.466892), term='cluster1')
FS_4 = FuzzySet(function=Gaussian_MF(5.384763, 267.420831), term='cluster2')
MF_ZN = LinguisticVariable([FS_3, FS_4], concept='ZN' , universe_of_discourse=(0.0, 95.0))
FS.add_linguistic_variable('ZN', MF_ZN)

FS_5 = FuzzySet(function=Gaussian_MF(21.697913, 12.279049), term='cluster1')
FS_6 = FuzzySet(function=Gaussian_MF(10.019186, 21.640178), term='cluster2')
MF_INDUS = LinguisticVariable([FS_5, FS_6], concept='INDUS' , universe_of_discourse=(0.46, 27.74))
FS.add_linguistic_variable('INDUS', MF_INDUS)

FS_7 = FuzzySet(function=Gaussian_MF(0.640061, 0.177867), term='cluster1')
FS_8 = FuzzySet(function=Gaussian_MF(0.513215, 0.641193), term='cluster2')
MF_NOX = LinguisticVariable([FS_7, FS_8], concept='NOX' , universe_of_discourse=(0.385, 0.871))
FS.add_linguistic_variable('NOX', MF_NOX)

FS_9 = FuzzySet(function=Gaussian_MF(5.156494, 2.144978), term='cluster1')
FS_10 = FuzzySet(function=Gaussian_MF(7.140239, 2.143417), term='cluster2')
MF_RM = LinguisticVariable([FS_9, FS_10], concept='RM' , universe_of_discourse=(3.561, 8.725))
FS.add_linguistic_variable('RM', MF_RM)

FS_11 = FuzzySet(function=Gaussian_MF(72.889421, 40.461023), term='cluster1')
FS_12 = FuzzySet(function=Gaussian_MF(58.145105, 232.027708), term='cluster2')
MF_AGE = LinguisticVariable([FS_11, FS_12], concept='AGE' , universe_of_discourse=(2.9, 100.0))
FS.add_linguistic_variable('AGE', MF_AGE)

FS_13 = FuzzySet(function=Gaussian_MF(2.465663, 3.499611), term='cluster1')
FS_14 = FuzzySet(function=Gaussian_MF(6.532438, 9.075292), term='cluster2')
MF_DIS = LinguisticVariable([FS_13, FS_14], concept='DIS' , universe_of_discourse=(1.1296, 10.7103))
FS.add_linguistic_variable('DIS', MF_DIS)

FS_15 = FuzzySet(function=Gaussian_MF(16.120297, 14.343822), term='cluster1')
FS_16 = FuzzySet(function=Gaussian_MF(5.073687, 9.223764), term='cluster2')
MF_RAD = LinguisticVariable([FS_15, FS_16], concept='RAD' , universe_of_discourse=(1.0, 24.0))
FS.add_linguistic_variable('RAD', MF_RAD)

FS_17 = FuzzySet(function=Gaussian_MF(709.615325, 171.804083), term='cluster1')
FS_18 = FuzzySet(function=Gaussian_MF(290.101652, 177.862865), term='cluster2')
MF_TAX = LinguisticVariable([FS_17, FS_18], concept='TAX' , universe_of_discourse=(188.0, 711.0))
FS.add_linguistic_variable('TAX', MF_TAX)

FS_19 = FuzzySet(function=Gaussian_MF(19.756479, 1.067483), term='cluster1')
FS_20 = FuzzySet(function=Gaussian_MF(17.058101, 22.344243), term='cluster2')
MF_PTRATIO = LinguisticVariable([FS_19, FS_20], concept='PTRATIO' , universe_of_discourse=(12.6, 22.0))
FS.add_linguistic_variable('PTRATIO', MF_PTRATIO)

FS_21 = FuzzySet(function=Gaussian_MF(24.382103, 50.487911), term='cluster1')
FS_22 = FuzzySet(function=Gaussian_MF(14.124280, 20.217594), term='cluster2')
MF_LSTAT = LinguisticVariable([FS_21, FS_22], concept='LSTAT' , universe_of_discourse=(1.92, 37.97))
FS.add_linguistic_variable('LSTAT', MF_LSTAT)


# end of automatically generated code #

FS.produce_figure("./figures/simpful_2_clusters.png")