# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (CRIM IS cluster1) AND (ZN IS cluster1) AND (INDUS IS cluster1) AND (NOX IS cluster1) AND (RM IS cluster1) AND (AGE IS cluster1) AND (DIS IS cluster1) AND (RAD IS cluster1) AND (TAX IS cluster1) AND (PTRATIO IS cluster1) AND (LSTAT IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (CRIM IS cluster2) AND (ZN IS cluster2) AND (INDUS IS cluster2) AND (NOX IS cluster2) AND (RM IS cluster2) AND (AGE IS cluster2) AND (DIS IS cluster2) AND (RAD IS cluster2) AND (TAX IS cluster2) AND (PTRATIO IS cluster2) AND (LSTAT IS cluster2) THEN (OUTPUT IS fun2)"
RULE3 = "IF (CRIM IS cluster3) AND (ZN IS cluster3) AND (INDUS IS cluster3) AND (NOX IS cluster3) AND (RM IS cluster3) AND (AGE IS cluster3) AND (DIS IS cluster3) AND (RAD IS cluster3) AND (TAX IS cluster3) AND (PTRATIO IS cluster3) AND (LSTAT IS cluster3) THEN (OUTPUT IS fun3)"
FS.add_rules([RULE1, RULE2, RULE3])

FS.set_output_function('fun1', '2.960410e-01*CRIM+3.189527e-02*ZN+1.724598e-02*INDUS+-5.728975e+00*NOX+8.086473e+00*RM+-4.987565e-02*AGE+-8.895017e-01*DIS+3.964570e-01*RAD+-1.018066e-02*TAX+-4.674333e-01*PTRATIO+-9.824079e-02*LSTAT+-7.143147e+00')
FS.set_output_function('fun2', '-2.109259e-01*CRIM+2.369007e-01*ZN+-1.326547e-01*INDUS+-3.523139e+01*NOX+-1.007914e+00*RM+4.501771e-03*AGE+-4.740446e+00*DIS+3.184194e-01*RAD+-9.495168e-03*TAX+2.151269e-01*PTRATIO+-9.795253e-01*LSTAT+7.328769e+01')
FS.set_output_function('fun3', '3.960343e-04*CRIM+0.000000e+00*ZN+4.771371e-04*INDUS+1.618576e-05*NOX+1.398196e-04*RM+2.564941e-03*AGE+5.537690e-05*DIS+6.326680e-04*RAD+1.755654e-02*TAX+5.324955e-04*PTRATIO+6.566566e-04*LSTAT+2.636117e-05')

FS_1 = FuzzySet(function=Gaussian_MF(-6.906719, 38.875204), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(25.785695, 113.561511), term='cluster2')
FS_3 = FuzzySet(function=Gaussian_MF(14.910598, 0.015098), term='cluster3')
MF_CRIM = LinguisticVariable([FS_1, FS_2, FS_3], concept='CRIM' , universe_of_discourse=(0.00632, 73.5341))
FS.add_linguistic_variable('CRIM', MF_CRIM)

FS_4 = FuzzySet(function=Gaussian_MF(-20.341828, 119.546202), term='cluster1')
FS_5 = FuzzySet(function=Gaussian_MF(-12.675506, 47.067510), term='cluster2')
FS_6 = FuzzySet(function=Gaussian_MF(-5.755343, 139.076159), term='cluster3')
MF_ZN = LinguisticVariable([FS_4, FS_5, FS_6], concept='ZN' , universe_of_discourse=(0.0, 95.0))
FS.add_linguistic_variable('ZN', MF_ZN)

FS_7 = FuzzySet(function=Gaussian_MF(11.885985, 10.918041), term='cluster1')
FS_8 = FuzzySet(function=Gaussian_MF(21.937106, 9.989997), term='cluster2')
FS_9 = FuzzySet(function=Gaussian_MF(9.770937, 18.052127), term='cluster3')
MF_INDUS = LinguisticVariable([FS_7, FS_8, FS_9], concept='INDUS' , universe_of_discourse=(0.46, 27.74))
FS.add_linguistic_variable('INDUS', MF_INDUS)

FS_10 = FuzzySet(function=Gaussian_MF(0.697686, 0.422810), term='cluster1')
FS_11 = FuzzySet(function=Gaussian_MF(0.645724, 0.155882), term='cluster2')
FS_12 = FuzzySet(function=Gaussian_MF(0.525963, 0.199288), term='cluster3')
MF_NOX = LinguisticVariable([FS_10, FS_11, FS_12], concept='NOX' , universe_of_discourse=(0.385, 0.871))
FS.add_linguistic_variable('NOX', MF_NOX)

FS_13 = FuzzySet(function=Gaussian_MF(6.740220, 1.852051), term='cluster1')
FS_14 = FuzzySet(function=Gaussian_MF(5.117570, 2.016222), term='cluster2')
FS_15 = FuzzySet(function=Gaussian_MF(7.112633, 1.730517), term='cluster3')
MF_RM = LinguisticVariable([FS_13, FS_14, FS_15], concept='RM' , universe_of_discourse=(3.561, 8.725))
FS.add_linguistic_variable('RM', MF_RM)

FS_16 = FuzzySet(function=Gaussian_MF(70.441476, 77.151951), term='cluster1')
FS_17 = FuzzySet(function=Gaussian_MF(73.418369, 38.225634), term='cluster2')
FS_18 = FuzzySet(function=Gaussian_MF(55.397681, 94.084694), term='cluster3')
MF_AGE = LinguisticVariable([FS_16, FS_17, FS_18], concept='AGE' , universe_of_discourse=(2.9, 100.0))
FS.add_linguistic_variable('AGE', MF_AGE)

FS_19 = FuzzySet(function=Gaussian_MF(4.625996, 6.289851), term='cluster1')
FS_20 = FuzzySet(function=Gaussian_MF(2.638156, 2.694691), term='cluster2')
FS_21 = FuzzySet(function=Gaussian_MF(6.813055, 6.322131), term='cluster3')
MF_DIS = LinguisticVariable([FS_19, FS_20, FS_21], concept='DIS' , universe_of_discourse=(1.1296, 12.1265))
FS.add_linguistic_variable('DIS', MF_DIS)

FS_22 = FuzzySet(function=Gaussian_MF(4.636103, 2.377579), term='cluster1')
FS_23 = FuzzySet(function=Gaussian_MF(16.296659, 12.709357), term='cluster2')
FS_24 = FuzzySet(function=Gaussian_MF(5.064508, 9.126927), term='cluster3')
MF_RAD = LinguisticVariable([FS_22, FS_23, FS_24], concept='RAD' , universe_of_discourse=(1.0, 24.0))
FS.add_linguistic_variable('RAD', MF_RAD)

FS_25 = FuzzySet(function=Gaussian_MF(425.855205, 91.199789), term='cluster1')
FS_26 = FuzzySet(function=Gaussian_MF(704.423396, 129.034610), term='cluster2')
FS_27 = FuzzySet(function=Gaussian_MF(241.463175, 96.547939), term='cluster3')
MF_TAX = LinguisticVariable([FS_25, FS_26, FS_27], concept='TAX' , universe_of_discourse=(187.0, 711.0))
FS.add_linguistic_variable('TAX', MF_TAX)

FS_28 = FuzzySet(function=Gaussian_MF(17.798986, 5.142347), term='cluster1')
FS_29 = FuzzySet(function=Gaussian_MF(19.610463, 0.955262), term='cluster2')
FS_30 = FuzzySet(function=Gaussian_MF(16.990813, 7.679823), term='cluster3')
MF_PTRATIO = LinguisticVariable([FS_28, FS_29, FS_30], concept='PTRATIO' , universe_of_discourse=(12.6, 22.0))
FS.add_linguistic_variable('PTRATIO', MF_PTRATIO)

FS_31 = FuzzySet(function=Gaussian_MF(17.873001, 19.146277), term='cluster1')
FS_32 = FuzzySet(function=Gaussian_MF(24.428095, 35.195001), term='cluster2')
FS_33 = FuzzySet(function=Gaussian_MF(12.928086, 15.400695), term='cluster3')
MF_LSTAT = LinguisticVariable([FS_31, FS_32, FS_33], concept='LSTAT' , universe_of_discourse=(1.98, 37.97))
FS.add_linguistic_variable('LSTAT', MF_LSTAT)


# end of automatically generated code #

FS.produce_figure("./figures/simpful_3_clusters.png")